### ISSUE TITLE
AHC010 の結果が反映されていない

### ISSUE THREAD

**Issue by siman-man** [qropa/extended-gp30-ranking#1]
[AHC010](https://atcoder.jp/contests/ahc010/standings/extended) は延長戦に対応していますが、ページには反映されていないように見えます。

**Comment by siman-man** [comment]
[AHC010](https://atcoder.jp/contests/ahc010/standings/extended) は延長戦に対応していますが、ページには反映されていないように見えます。

**Comment by qropa** [comment]
ご報告ありがとうございます。
AHC010を反映させました。
